### ISSUE TITLE
Make Side bar : `position: sticky;`

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/simple_discussion#5]
Make sidebar `position: sticky;` for easy accessibility and improved appearance.
### Video of current functionality :
https://github.com/CircuitVerse/simple_discussion/assets/77102885/6c26b3ed-4651-433a-9811-1e60c5befc26

### Video of Solution :

https://github.com/CircuitVerse/simple_discussion/assets/77102885/fd4fddd3-2105-42d4-9c96-5ff08d8f152b

**Comment by tanmoysrt** [comment]
Closing this as complegted by PR #6
